// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos-layout/internal/conf"
	"github.com/go-kratos/kratos-layout/internal/server"
	"github.com/go-kratos/kratos-layout/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, discover *conf.Discover, logger log.Logger, discovery registry.Discovery) (*kratos.App, func(), error) {
	userClient := service.NewUserClient(discover, discovery)
	greeterService := service.NewGreeterService(userClient)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
